[package]
name = "football_manager_tui"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui.workspace = true
crossterm.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
