[workspace]
members = ["tui", "basic-emulator"]
resolver = "2"

[workspace.dependencies]
ratatui = "0.28"
crossterm = "0.28"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
